export const COUNTER_CHANGE = 'COUNTER_CHANGE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const SCAN_PRINTER = 'SCAN_PRINTER';
export const RECEIVE_PAIRED_PRINTER = 'RECEIVE_PAIRED_PRINTER';
export const SELECT_PRINTER = 'SELECT_PRINTER';
